services:
  client:
    container_name: client
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_LOG_LEVEL=DEBUG
    volumes:
      - ./data/movies.csv:/app/movies.csv
      - ./data/ratings.csv:/app/ratings.csv
      - ./data/credits.csv:/app/credits.csv
    networks:
      - gateway_distribuidos

networks:
  gateway_distribuidos:
    external: true