name: tp0
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
    - 15672:15672
    networks:
    - testing_net
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    networks:
    - testing_net
  client:
    container_name: client
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    networks:
    - testing_net
    depends_on:
    - server
  filter1:
    container_name: filter1
    image: filter:latest
    entrypoint: python3 workers/filter.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=FILTER
    - CONSULTAS=1,2,3,4,5
    - EOF_ENVIAR=3:1,4:1,5:1
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  joiner1:
    container_name: joiner1
    image: joiner:latest
    entrypoint: python3 workers/joiner.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=JOINER
    - CONSULTAS=3,4
    - EOF_ESPERADOS=3:1,4:1
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  aggregator1:
    container_name: aggregator1
    image: aggregator:latest
    entrypoint: python3 workers/aggregator.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=AGGREGATOR
    - CONSULTAS=2,3,4,5
    - EOF_ESPERADOS=2:1,3:1,4:1,5:1
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  pnl1:
    container_name: pnl1
    image: pnl:latest
    entrypoint: python3 workers/pnl.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=PNL
    - CONSULTAS=5
    - EOF_ESPERADOS=5:1
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
