name: tp0
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
    - 15672:15672
    networks:
    - testing_net
    logging:
      driver: "none"
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    networks:
    - testing_net
  client:
    container_name: client
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=1
    - CLI_LOG_LEVEL=DEBUG
    networks:
    - testing_net
    depends_on:
    - server
  filter1:
    container_name: filter1
    image: filter:latest
    entrypoint: python3 workers/filter.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=FILTER
    - CONSULTAS=1,5
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  filter2:
    container_name: filter2
    image: filter:latest
    entrypoint: python3 workers/filter.py
    environment:
    - WORKER_ID=2
    - WORKER_TYPE=FILTER
    - CONSULTAS=2
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  filter3:
    container_name: filter3
    image: filter:latest
    entrypoint: python3 workers/filter.py
    environment:
    - WORKER_ID=3
    - WORKER_TYPE=FILTER
    - CONSULTAS=3
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  filter4:
    container_name: filter4
    image: filter:latest
    entrypoint: python3 workers/filter.py
    environment:
    - WORKER_ID=4
    - WORKER_TYPE=FILTER
    - CONSULTAS=4
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  aggregator1:
    container_name: aggregator1
    image: aggregator:latest
    entrypoint: python3 workers/aggregator.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=AGGREGATOR
    - CONSULTAS=1,3,5
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  aggregator2:
    container_name: aggregator2
    image: aggregator:latest
    entrypoint: python3 workers/aggregator.py
    environment:
    - WORKER_ID=2
    - WORKER_TYPE=AGGREGATOR
    - CONSULTAS=2,4
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  pnl1:
    container_name: pnl1
    image: pnl:latest
    entrypoint: python3 workers/pnl.py
    environment:
    - WORKER_ID=1
    - WORKER_TYPE=PNL
    - CONSULTAS=5
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  pnl2:
    container_name: pnl2
    image: pnl:latest
    entrypoint: python3 workers/pnl.py
    environment:
    - WORKER_ID=2
    - WORKER_TYPE=PNL
    - CONSULTAS=5
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
  pnl3:
    container_name: pnl3
    image: pnl:latest
    entrypoint: python3 workers/pnl.py
    environment:
    - WORKER_ID=3
    - WORKER_TYPE=PNL
    - CONSULTAS=5
    networks:
    - testing_net
    depends_on:
    - server
    - rabbitmq
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
