services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    networks:
      - distribuidos
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  input_gateway:
    container_name: input_gateway
    image: gateway:latest
    entrypoint: /input_gateway
    environment:
      - CLI_LOG_LEVEL=DEBUG
    ports:
      - "5000:5000"  # Movies
      - "5001:5001"  # Credits
      - "5002:5002"  # Ratings
    networks:
      - distribuidos
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq

networks:
  distribuidos:
    ipam:
      driver: default
      config:
        - subnet: 172.25.126.0/24