query: "ARGENTINIAN-SPANISH-PRODUCTIONS"
gateway:
  input_movies_address: "input_gateway:5000"
  input_credits_address: "input_gateway:5001"
  input_ratings_address: "input_gateway:5002"
  output_address: "output_gateway:5000"
file:
  movies_path: "./app/movies.csv"
  credits_path: "./app/credits.csv"
  ratings_path: "./app/ratings.csv"
batch:
  max_size: 1000
  max_amount: 8192
log:
  level: "INFO"