gateway:
  movies_address: ":5000"
  credits_address: ":5001"
  ratings_address: ":5002"
log:
  level: "INFO"

rabbitmq:
  address: "amqp://guest:guest@rabbitmq/"
  filter_queues:
    argentinian-spanish-productions: "filter_input"
    top-investing-countries: "filter_input"
    top-argentinian-movies-by-rating: "filter_input"
    top-argentinian-actors: "filter_input"
    sentiment-analysis: "filter_input"
  join_queues:
    top-argentinian-movies-by-rating: "joiner_input"
    top-argentinian-actors: "joiner_input"
